apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: kapp-controller.community.tanzu.vmware.com.0.30.3
spec:
  refName: kapp-controller.community.tanzu.vmware.com
  version: 0.30.3
  releaseNotes: "kapp-controller 0.30.3 https://github.com/vmware-tanzu/carvel-kapp-controller"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/kapp-controller@sha256:b13db3c32b89de10c3bd373803f81ec8e1c8179e4909c1d90c2fcc1b3c718e06
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
